# Plot XVG (--> CSV+strip xmgrace headers) files generated by various GROMACS tools after processing the output of a simulation.

library(tidyverse)


setwd("/home/user/Documents/MD/Plots")


ps2ns <- function(x)
{
  return(x/1000)
}

# ALL IMAGES SAVED IN 564 X 364 RESOLUTION IN TIFF FORMAT.
# THEN ADJUSTED AND CROPPED.

# Rmsd in nm/ns
iso1_rmsd <-  read_delim("rmsd-iso1-100ns.csv", " ", col_names = FALSE)
colnames(iso1_rmsd) <- c("Time", "RMSD")

iso2_rmsd <-  read_delim("rmsd-iso2-100ns.csv", " ", col_names = FALSE)
colnames(iso2_rmsd) <- c("Time", "RMSD")

# Maxdist in nm/ns
# WARNING!! THIS IS NOT WHAT WE ARE LOOKING FOR!
iso1_maxdist <-  read_delim("maxdist-iso1-100ns.csv", " ", col_names = FALSE)
colnames(iso1_maxdist) <- c("Time", "Distance")

iso2_maxdist <-  read_delim("maxdist-iso2-100ns.csv", " ", col_names = FALSE)
colnames(iso2_maxdist) <- c("Time", "Distance")

# Rmsf in Residue/nm
iso1_fluct <-  read_delim("rmsf-iso1-100ns.csv", " ", col_names = FALSE)
colnames(iso1_fluct) <- c("Residue", "RMSF")

iso2_fluct <-  read_delim("rmsf-iso2-100ns.csv", " ", col_names = FALSE)
colnames(iso2_fluct) <- c("Residue", "RMSF")

# SASA in ps/nm2
iso1_sasa <-  read_delim("sasa-iso1-100ns.csv", " ", col_names = FALSE)
tmp1 <- as.data.frame(cbind(ps2ns(as.numeric(iso1_sasa$X1)), iso1_sasa$X2))
colnames(tmp1) <- c("Time", "SASA")
iso1_sasa <- tmp1
rm(tmp1)

iso2_sasa <-  read_delim("sasa-iso2-100ns.csv", " ", col_names = FALSE)
tmp2 <- as.data.frame(cbind(ps2ns(as.numeric(iso2_sasa$X1)), iso2_sasa$X2))
colnames(tmp2) <- c("Time", "SASA")
iso2_sasa <- tmp2
rm(tmp2)

iso1_gyra <-  read_tsv("gyr-iso1-100ns.csv", col_names = FALSE)
tmp3 <- as.data.frame(cbind(ps2ns(as.numeric(iso1_gyra$X1)), iso1_gyra$X2))
colnames(tmp3) <- c("Time", "Rg")
iso1_gyra <- tmp3
rm(tmp3)

iso2_gyra <-  read_tsv("gyr-iso2-100ns.csv",col_names = FALSE)
tmp4 <- as.data.frame(cbind(ps2ns(as.numeric(iso2_gyra$X1)), iso2_gyra$X2))
colnames(tmp4) <- c("Time", "Rg")
iso2_gyra <- tmp4
rm(tmp4)

# Average distance of centre of masses of protein and ligand.
# ATTENTION! THIS IS WHAT WE ARE LOOKING FOR! (nm/ns)
iso1_avgcomdist <-  read_csv("com-avgdist-iso1.csv", col_names = FALSE)
colnames(iso1_avgcomdist) <- c("Time", "Distance")

iso2_avgcomdist <-  read_csv("com-avgdist-iso2.csv", col_names = FALSE)
colnames(iso2_avgcomdist) <- c("Time", "Distance")


# Convert data frames from char to numeric
iso1_rmsd <- iso1_rmsd %>% sapply(as.numeric) %>% as.data.frame()
iso2_rmsd <- iso2_rmsd %>% sapply(as.numeric) %>% as.data.frame()
iso1_fluct <- iso1_fluct %>% sapply(as.numeric) %>% as.data.frame()
iso2_fluct <- iso2_fluct %>% sapply(as.numeric) %>% as.data.frame()
iso1_maxdist <- iso1_maxdist %>% sapply(as.numeric) %>% as.data.frame()
iso2_maxdist <- iso2_maxdist %>% sapply(as.numeric) %>% as.data.frame()

iso1_sasa <- as.data.frame(cbind(as.numeric(as.character(iso1_sasa$Time)), as.numeric(as.character(iso1_sasa$SASA))))
colnames(iso1_sasa) <- c("Time", "SASA")

iso2_sasa <- as.data.frame(cbind(as.numeric(as.character(iso2_sasa$Time)), as.numeric(as.character(iso2_sasa$SASA))))
colnames(iso2_sasa) <- c("Time", "SASA")

iso1_gyra <- as.data.frame(cbind(as.numeric(as.character(iso1_gyra$Time)), as.numeric(as.character(iso1_gyra$Rg))))
colnames(iso1_gyra) <- c("Time", "Rg")

iso2_gyra <- as.data.frame(cbind(as.numeric(as.character(iso2_gyra$Time)), as.numeric(as.character(iso2_gyra$Rg))))
colnames(iso2_gyra) <- c("Time", "Rg")



plot(iso1_sasa$Time, iso1_sasa$SASA, type="l", col="#27afd8", xlab="Time(ns)", ylab="SASA (nm^2)")
lines(iso2_sasa$Time, iso2_sasa$SASA, type="l", col="#ff7373")
legend("bottomright", legend=c("Isoform 1 ", "Isoform 2 "), col=c("#27afd8", "#ff7373"), lty=1, cex=0.8, bty="n")



plot(iso1_maxdist$Time, iso1_maxdist$Distance, type="l", col="#27afd8", ylim=c(4,6.5), xlab="Time(ns)", ylab="Distance (nm)")
lines(iso2_maxdist$Time, iso2_maxdist$Distance, type="l", col="#ff7373")
legend("bottomright", legend=c("Isoform 1 ", "Isoform 2 "), col=c("#27afd8", "#ff7373"), lty=1, cex=0.8, bty="n")


plot(iso1_fluct$Residue, iso1_fluct$RMSF, type="l", col="#27afd8", xlab="#Residue", ylab="RMSF (nm)", lwd=3)
lines(iso2_fluct$Residue, iso2_fluct$RMSF, type="l", col="#ff7373", lwd=3)
legend("topright", legend=c("Isoform 1 ", "Isoform 2 "), col=c("#27afd8", "#ff7373"), lty=1, cex=0.8, bty="n")


plot(iso1_rmsd$Time, iso1_rmsd$RMSD, type="l", col="#27afd8", xlab="Time (ns)", ylab="RMSD (nm)")
lines(iso2_rmsd$Time, iso2_rmsd$RMSD, type="l", col="#ff7373")
legend("bottomright", legend=c("Isoform 1 ", "Isoform 2 "), col=c("#27afd8", "#ff7373"), lty=1, cex=0.8, bty="n")



plot(iso1_gyra$Time, iso1_gyra$Rg, type="l", col="#27afd8", xlab="Time (ns)", ylab="Rg (nm)")
lines(iso2_gyra$Time, iso2_gyra$Rg, type="l", col="#ff7373")
legend("bottomright", legend=c("Isoform 1 ", "Isoform 2 "), col=c("#27afd8", "#ff7373"), lty=1, cex=0.8, bty="n")


plot(iso1_avgcomdist$Time, iso1_avgcomdist$Distance, type="l", col="#27afd8", ylim=c(0.2, 2.0), xlab="Time (ns)", ylab="Avg. distance (nm)")
lines(iso2_avgcomdist$Time, iso2_avgcomdist$Distance, type="l", col="#ff7373")
legend("bottomright", legend=c("Isoform 1 & Ligand    ", "Isoform 2 & Ligand    "), col=c("#27afd8", "#ff7373"), lty=1, cex=0.8, bty="n")

